### ISSUE TITLE
URL validator does not accept fragments

### ISSUE THREAD

**Issue by cgrigis** [crdoconnor/strictyaml#141]
A URL with a fragment fails to validate:

```
>>> from strictyaml import Map, Url, load
>>> schema = Map({"url": Url()})
>>>
>>> load("url: https://example.com/bla", schema)
YAML({'url': 'https://example.com/bla'})
>>>
>>> load("url: https://example.com/bla#header", schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/parser.py", line 318, in load
    return generic_load(yaml_string, schema=schema, label=label)
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/parser.py", line 296, in generic_load
    return schema(YAMLChunk(document, label=label))
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/validators.py", line 17, in __call__
    self.validate(chunk)
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/compound.py", line 165, in validate
    value.process(self._validator_dict[yaml_key.scalar](value))
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/scalar.py", line 27, in __call__
    return YAML(chunk, validator=self)
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/representation.py", line 63, in __init__
    self._value = validator.validate(value)
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/scalar.py", line 30, in validate
    return self.validate_scalar(chunk)
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/scalar.py", line 128, in validate_scalar
    self._matching_message, "found non-matching string"
  File "/home/cgrigis/C4DT/Projects/strictyaml/strictyaml/yamllocation.py", line 47, in expecting_but_found
    self,
strictyaml.exceptions.YAMLValidationError: when expecting a url
found non-matching string
  in "<unicode string>", line 1, column 1:
    url: https://example.com/bla#header
     ^ (line: 1)
```

Probably related to 5beb1eaeb9fa2c23adc9a548a164e4d539f2acfc... it seems the new regex from https://urlregex.com/ does not cover fragments?

**Comment by cgrigis** [comment]
@crdoconnor Any chance to have a quick look at this?  Thank you!

**Comment by crdoconnor** [comment]
Yes, I'll take a look tonight.

**Comment by cgrigis** [comment]
Thanks! :)

**Comment by crdoconnor** [comment]
Hi,

Sorry I havent been very active on this I've had a lot on recently.

That sounds like a good idea though.
