### ISSUE TITLE
1.7.0 is broken (cannot import name 'ruamel' from partially initialized module 'strictyaml')

### ISSUE THREAD

**Issue by mbergal** [crdoconnor/strictyaml#193]
```
Python 3.11.1 (main, Jan 30 2023, 19:14:50) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import strictyaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/misha/.pyenv/versions/3.11.1/lib/python3.11/site-packages/strictyaml/__init__.py", line 2, in <module>
    from strictyaml.parser import load
  File "/home/misha/.pyenv/versions/3.11.1/lib/python3.11/site-packages/strictyaml/parser.py", line 6, in <module>
    from strictyaml import ruamel as ruamelyaml
ImportError: cannot import name 'ruamel' from partially initialized module 'strictyaml' (most likely due to a circular import) (/home/misha/.pyenv/versions/3.11.1/lib/python3.11/site-packages/strictyaml/__init__
py)
```

**Comment by prositen** [comment]
I got the same problem in a fresh virtualenv.

```
anna@carbuncle:~/kod$ mkvirtualenv -p python3.10 strictyaml-test
created virtual environment CPython3.10.6.final.0-64 in 182ms
  creator CPython3Posix(dest=/home/anna/kod/.venv/strictyaml-test, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/anna/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating /home/anna/kod/.venv/strictyaml-test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/anna/kod/.venv/strictyaml-test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/anna/kod/.venv/strictyaml-test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/anna/kod/.venv/strictyaml-test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/anna/kod/.venv/strictyaml-test/bin/get_env_details
(strictyaml-test) anna@carbuncle:~/kod$ pip install --no-cache-dir strictyaml==1.7.0
Collecting strictyaml==1.7.0
  Downloading strictyaml-1.7.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dateutil>=2.6.0
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 5.4 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: strictyaml
  Building wheel for strictyaml (pyproject.toml) ... done
  Created wheel for strictyaml: filename=strictyaml-1.7.0-py3-none-any.whl size=26651 sha256=4d35897c75df0dc16b4a2057dca10972d3bf0e3c5f16c07933fa342403fe9445
  Stored in directory: /tmp/pip-ephem-wheel-cache-vpqyd4ls/wheels/95/ad/1b/c1656b5fd8115ae5b0cedbd4c92e6cfadaa6428d7bebf13c76
Successfully built strictyaml
Installing collected packages: six, python-dateutil, strictyaml
Successfully installed python-dateutil-2.8.2 six-1.16.0 strictyaml-1.7.0
(strictyaml-test) anna@carbuncle:~/kod$ python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import strictyaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anna/kod/.venv/strictyaml-test/lib/python3.10/site-packages/strictyaml/__init__.py", line 2, in <module>
    from strictyaml.parser import load
  File "/home/anna/kod/.venv/strictyaml-test/lib/python3.10/site-packages/strictyaml/parser.py", line 6, in <module>
    from strictyaml import ruamel as ruamelyaml
ImportError: cannot import name 'ruamel' from partially initialized module 'strictyaml' (most likely due to a circular import) (/home/anna/kod/.venv/strictyaml-test/lib/python3.10/site-packages/strictyaml/__init__.py)
```

**Comment by crdoconnor** [comment]
Ok I managed to reproduce in another virtualenv. I've yanked the release until I figure out what is going on.
