### ISSUE TITLE
Empty document not allowed to be parsed with all-optional fields schema

### ISSUE THREAD

**Issue by gjcarneiro** [crdoconnor/strictyaml#33]
Found when working on gjcarneiro/yacron#19:

When there is a schema, and all outer fields are optional, it's strictyaml doesn't allow parsing the empty document.  Example:

```python
>>> from strictyaml import Map, Str, Optional as Opt
>>> import strictyaml
>>> strictyaml.load("", Map({Opt("foo"): Str()}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gjc/projects/yacron/env/lib/python3.6/site-packages/strictyaml-0.11.7-py3.6.egg/strictyaml/parser.py", line 276, in load
    return schema(YAMLChunk(document, label=label))
  File "/home/gjc/projects/yacron/env/lib/python3.6/site-packages/strictyaml-0.11.7-py3.6.egg/strictyaml/validators.py", line 14, in __call__
    self.validate(chunk)
  File "/home/gjc/projects/yacron/env/lib/python3.6/site-packages/strictyaml-0.11.7-py3.6.egg/strictyaml/compound.py", line 99, in validate
    items = chunk.expect_mapping()
  File "/home/gjc/projects/yacron/env/lib/python3.6/site-packages/strictyaml-0.11.7-py3.6.egg/strictyaml/yamllocation.py", line 87, in expect_mapping
    "found {0}".format(self.found())
  File "/home/gjc/projects/yacron/env/lib/python3.6/site-packages/strictyaml-0.11.7-py3.6.egg/strictyaml/yamllocation.py", line 34, in expecting_but_found
    self
strictyaml.exceptions.YAMLValidationError: when expecting a mapping
found a blank string
  in "<unicode string>", line 1, column 1:
    ''
     ^ (line: 1)
>>> 
```

**Comment by crdoconnor** [comment]
Does:

    >>> from strictyaml import Map, Str, Optional as Opt, load, EmptyDict
    >>> load("", EmptyDict() | Map({Opt("foo"): Str()}))

Work for you?

**Comment by gjcarneiro** [comment]
It does!  If that is what I was supposed to do, never mind then.

**Comment by crdoconnor** [comment]
Yeah, semantically I thought that it made sense to always expect some kind of mapping for Map unless explicitly directed otherwise.

I see your point about having all optional keys and rejecting 'no keys' being confusing though.

**Comment by gjcarneiro** [comment]
Yes, it confused me, I wouldn't mind relaxing the Map requirements.

**Comment by bwoodsend** [comment]
The `EmptyDict() | Map(...)` workaround doesn't play well with the `default` parameter to `Optional()`.

```python
>>> from strictyaml import Map, Bool, Optional as Opt, load, EmptyDict
>>> load("", EmptyDict() | Map({Opt("foo", default=True): Bool()}))
```

Granted that I could parse the YAML then use `parsed.get("foo", True)` but that kinda defeats the point in `Optional()` having a `default` argument.

**Comment by bwoodsend** [comment]
Also, it breaks if the YAML contains just `\n`:
```python
>>> load("\n", EmptyDict() | Map({Opt("foo"): Str()}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/parser.py", line 323, in load
    return generic_load(yaml_string, schema=schema, label=label)
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/parser.py", line 301, in generic_load
    return schema(YAMLChunk(document, label=label))
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/validators.py", line 112, in __call__
    result = self._validator_b(chunk)
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/validators.py", line 17, in __call__
    self.validate(chunk)
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/compound.py", line 161, in validate
    items = chunk.expect_mapping()
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/yamllocation.py", line 110, in expect_mapping
    self.expecting_but_found(
  File "/home/brenainn/.pyenv/versions/3.10.4/lib/python3.10/site-packages/strictyaml/yamllocation.py", line 44, in expecting_but_found
    raise YAMLValidationError(
strictyaml.exceptions.YAMLValidationError: when expecting a mapping
found an arbitrary number
  in "<unicode string>", line 1, column 1:
    "\n"
     ^ (line: 1)

when expecting a mapping
found an arbitrary number
  in "<unicode string>", line 1, column 1:
    "\n"
     ^ (line: 1)
```

**Comment by crdoconnor** [comment]
Thanks for bringing these things up. I'll take a look at the weekend.
