### ISSUE TITLE
Assignment in 1.0.5 not working when multiline strings are present

### ISSUE THREAD

**Issue by paolieri** [crdoconnor/strictyaml#86]
The following code 

```
from strictyaml import Str, Map, load

snippet = '''
a: some
b: |
  text
'''

schema = Map({"a": Str(), "b": Str()})
parsed = load(snippet, schema)
parsed['a'] = 'changed'
print(parsed.as_yaml())
```
prints
```
a: changed
b: |
  text
```
in `1.0.4` but an exception is thrown with StrictYAML `1.0.5`:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    parsed['a'] = 'changed'
  File "/Users/me/.local/share/virtualenvs/test-a8l4L8Gp/lib/python3.7/site-packages/strictyaml/representation.py", line 214, in __setitem__
    yaml_value = YAMLChunk(self._validator.to_yaml(old_data))
  File "/Users/me/.local/share/virtualenvs/test-a8l4L8Gp/lib/python3.7/site-packages/strictyaml/compound.py", line 208, in to_yaml
    for key, value in data.items()
  File "/Users/me/.local/share/virtualenvs/test-a8l4L8Gp/lib/python3.7/site-packages/strictyaml/compound.py", line 211, in <listcomp>
    and value != self._defaults[key]
  File "/Users/me/.local/share/virtualenvs/test-a8l4L8Gp/lib/python3.7/site-packages/strictyaml/scalar.py", line 151, in to_yaml
    raise YAMLSerializationError("'{}' is not a string".format(data))
strictyaml.exceptions.YAMLSerializationError: 'text
' is not a string
```
The problem seems to be assigning to a mapping when another one has a multiline property.

**Comment by crdoconnor** [comment]
Thank you! I'll take a look into it.

**Comment by hgomersall** [comment]
This is fixed and should probably be closed. I just got burnt by it, but was very pleased it has been fixed :+1:

**Comment by crdoconnor** [comment]
Thank Henry I'll do that.
